x-veld:
  code:
    # TODO
    about:
      description:
      topics:

services:
  veld_eval:
    build: .
    command: python3 /opt/glove/eval/python/evaluate.py
    environment:
      VOCAB_FILE: null
      VECTOR_FILE: null
      EVAL_FOLDER: null

