x-veld:
  code:
    # TODO
    about:
      description:
      topics:

services:
  veld_train:
    build: .
    volumes:
      - ./src/main/train/:/veld/code/
    command: /veld/code/train.sh
    environment:
      CORPUS: null
      VOCAB_FILE: null
      COOCCURRENCE_FILE: null
      COOCCURRENCE_SHUF_FILE: null
      SAVE_FILE: null
      VERBOSE: 2
      MEMORY: 4.0
      VOCAB_MIN_COUNT: 5
      VECTOR_SIZE: 50
      MAX_ITER: 15
      WINDOW_SIZE: 15
      BINARY: 2
      NUM_THREADS: 8
      X_MAX: 10

